dist: xenial  # required for newer (>= 3.7) Python versions
language: python
matrix:
  include:
    - name: "Python 2.7 on Xenial"
      python: 2.7
    - name: "Python 3.3 on Trusty"
      python: 3.3
      dist: trusty  # xenial does not support py3.3
    - name: "Python 3.4 on Xenial"
      python: 3.4
    - name: "Python 3.5 on Xenial"
      python: 3.5
    - name: "Python 3.6 on Xenial"
      python: 3.6
    - name: "Python 3.7 on Xenial"
      python: 3.7
    - name: "Python 3.8 on Xenial"
      python: 3.8
git:
  submodules: false
branches:
  only:
    - master
    - /^\d+\.\d+\.x$/  # allows building maintenance branches
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/  # allows building version tags
    - /^travis-.+$/  # allows branch names intended to test Travis changes/problems
sudo: false  # Enables running on faster infrastructure.
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade "setuptools<=39.2.0"  # last version to support Python 3.3
  - pip install --upgrade -r requirements.txt -r dev-requirements.txt
  - python setup.py develop
script:
  - make travis
env:
  - COVERALLS_PARALLEL=true
after_success:
  coveralls
notifications:
  webhooks:
    urls:
      - https://coveralls.io/webhook
deploy:
  provider: pypi
  username: dgw
  password:
    secure: PcF5m7TOmab/WgzKJtR5YW/SAarPSSJgq0kfgmTUZHvOnSHwlljyKEPu3V1m2Orl8HOrej1p6zCOCx61oRIYbVejOOEau6aQYeVJPtGRigGIYOV/cDpcb2YuldWLT6iKXmDeVTpeVa/Ku5YZJ536sADN41pGW78G/uFa6EDXaIQ=
  server: https://test.pypi.org/legacy/
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^travis\-.+$
    python: "3.6"
  allow_failure: true
